checksumBehavior: update
enableMessageNames: false
nodeLinker: node-modules

npmScopes:
  rahil-p:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://us-npm.pkg.dev/rahil-p/npm/"
    npmRegistryServer: "https://us-npm.pkg.dev/rahil-p/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
