version: "3"

services:
  site:
    build:
      context: ../../..
      dockerfile: services/site/docker/dev.Dockerfile
    environment:
      SITE_PORT: "80"
      SITE_URL: ${SITE_CONTENT_SECURITY_POLICY:-https://localhost}
      SITE_CONTENT_SECURITY_POLICY: ${SITE_CONTENT_SECURITY_POLICY:-}
      GOOGLE_TAGMANAGER_ID: ${GOOGLE_TAGMANAGER_ID:-}
      SENTRY_PROJECT: ${SENTRY_PROJECT:-}
      SENTRY_DSN: ${SENTRY_DSN:-}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-}
      CONTACT_EMAIL: ${CONTACT_EMAIL:-}
      SOCIAL_GITHUB_URL: ${SOCIAL_GITHUB_URL:-}
      SOCIAL_STACKOVERFLOW_URL: ${SOCIAL_STACKOVERFLOW_URL:-}
      SOCIAL_TWITTER_ID: ${SOCIAL_TWITTER_ID:-}
      SOCIAL_TWITTER_URL: ${SOCIAL_TWITTER_URL:-}
    ports:
      - "${SITE_PORT:-80}:80"
    volumes:
      - ../dist:/var/www:ro

