name: audit

on:
  workflow_dispatch

env:
  NODE_VERSION: '16.13.2'

jobs:
  audit-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: badges
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run Lighthouse Audit
        run: |-
          npx --yes lighthouse-badges \
            --save-report \
            --single-badge \
            --badge-style flat \
            --urls https://rahil-p.com \
            --output-path ${{ github.workspace }}/audits/lighthouse
      - name: Upload Badges
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-badges
          path: ${{ github.workspace }}/audits/lighthouse
      - name: Commit report
        run: |-
          git config --global user.name 'Rahil Patel'
          git config --global user.email '37254995+rahil-p@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -am "Automated Lighthouse audit report"
          git push origin badges
