name: audit

on:
  workflow_dispatch

jobs:
  audit-lighthouse:
    runs-on: ubuntu-latest
    container:
      image: emazzotta/lighthouse-badges:6014050
    steps:
      - name: Run Lighthouse Audit
        run: lighthouse-badges --urls https://rahil-p.com
      - name: Upload Badges
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-badges
          path: /home/chrome/reports
